title: Sam and Cora
email: sam.younger@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Where Sam & Cora store their public life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samandcora.com"
twitter_username: ayoungersam
github_username:  samyounger

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
    sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh
  - s3_website.yml
  - README.md

# Default layouts for pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author: "Sam Younger"
      published: true
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/images/posts"
    values:
      post-image: true
  - scope:
      path: "assets/images/wedding"
    values:
      wedding-image: true
